version: '3.9'


services:

  db-ctrlbee:
    image: postgres:15-alpine
    restart: always
    container_name: db-ctrlbee
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=ctrlbee'
    ports:
      - "127.0.0.1:5435:5435"
    expose:
      - "5435"
    command: -p 5435
    volumes:
      - db-ctrlbee:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ctrlbee:5435/ctrlbee
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - "8080"
volumes:
  db-ctrlbee: